wandb_version: 1

number_chargelevels:
  desc: null
  value: 19
number_spatial_nodes:
  desc: null
  value: 5
dataset:
  desc: null
  value: ../data/NY/5/NYC_5.json
mpc_horizon:
  desc: null
  value: 48
number_vehicles_per_node_init:
  desc: null
  value: 4
charging_stations:
  desc: null
  value:
  - true
  - true
  - true
  - true
  - true
licence:
  desc: null
  value: Justin
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.15.8
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1711446029.649452
    t:
      1:
      - 1
      - 55
      - 77
      2:
      - 1
      - 55
      - 77
      3:
      - 13
      - 16
      - 23
      4: 3.10.12
      5: 0.15.8
      8:
      - 5
